title: "Cameron Heather"
# subtitle: "PhD Student, University of Warwick"
description: ""
url: "https://camheather.githib.io"
baseurl: ""


remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-include-cache


# Author info (used in sidebar)
author:
  name: "Cameron Heather"
  # avatar: "/assets/images/avatar.jpg" # optional
  bio: "PhD student"
  - label: "University of Warwick"
    icon: "fas fa-university"
  location: "Coventry, UK"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:cameron.heather@warwick.ac.uk"
    # - label: "University of Warwick"
    #   icon: "fas fa-university"
    #   url: "https://www.university.edu"
    # - label: "Google Scholar"
    #   icon: "ai ai-google-scholar"
    #   url: "https://scholar.google.com/..."
    # - label: "ORCID"
    #   icon: "ai ai-orcid"
    #   url: "https://orcid.org/...."
    # - label: "GitHub"
    #   icon: "fab fa-github"
    #   url: "https://github.com/yourusername"

# Layout defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

# Markdown
markdown: kramdown
highlighter: rouge

# Navigation
include:
  - _pages
