title: "Cameron Heather"
# subtitle: "PhD Student, University of Warwick"
description: ""
url: "https://camheather.githib.io"
baseurl: ""


remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-include-cache


# Author info (used in sidebar)
author:
  name: "Cameron Heather"
  # avatar: "/assets/images/avatar.jpg" # optional
  bio: "<i class='fas fa-building-columns'></i> University of Warwick"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:cameron.heather@warwick.ac.uk"
    - label: "Department Profile"
      icon: "fa-solid fa-id-card"
      url: "https://warwick.ac.uk/fac/sci/maths/people/staff/heather/"
    # - label: "Google Scholar"
    #   icon: "ai ai-google-scholar"
    #   url: "https://scholar.google.com/..."
    # - label: "ORCID"
    #   icon: "ai ai-orcid"
    #   url: "https://orcid.org/...."
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/cameron-heather-8403113aa/"
    # - label: "GitHub"
    #   icon: "fab fa-github"
    #   url: "https://github.com/camheather"

# Layout defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

# Markdown
markdown: kramdown
highlighter: rouge

# Navigation
include:
  - _pages

atom_feed:
  hide: true
# footer:
#   links:
#     - label: "University of Warwick"
#       icon: "fas fa-building-columns"
#       url: "https://warwick.ac.uk/"
